// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  entityId: __t.u64().primaryKey().name("entity_id"),
  kind: __t.u16(),
  archetypeId: __t.u32().name("archetype_id"),
  zoneId: __t.u64().name("zone_id"),
  chunkX: __t.i32().name("chunk_x"),
  chunkY: __t.i32().name("chunk_y"),
  alive: __t.bool(),
});
