// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.object("EventLog", {
  eventId: __t.u64(),
  tsMs: __t.u64(),
  tick: __t.u64(),
  zoneId: __t.u64(),
  chunkX: __t.i32(),
  chunkY: __t.i32(),
  actorId: __t.option(__t.u64()),
  targetId: __t.option(__t.u64()),
  eventType: __t.u16(),
  payload: __t.byteArray(),
});


