// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.11.1 (commit bbfa851b45db7096aa2a69d7dbad84f52983559f).

/* eslint-disable */
/* tslint:disable */
import {
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TypeBuilder as __TypeBuilder,
  convertToAccessorMap as __convertToAccessorMap,
  procedureSchema as __procedureSchema,
  procedures as __procedures,
  reducerSchema as __reducerSchema,
  reducers as __reducers,
  schema as __schema,
  t as __t,
  table as __table,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type DbConnectionConfig as __DbConnectionConfig,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type Infer as __Infer,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type RemoteModule as __RemoteModule,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
  type SubscriptionHandleImpl as __SubscriptionHandleImpl,
} from "spacetimedb";

// Import and reexport all reducer arg types
import AddBackstoryFactReducer from "./add_backstory_fact_reducer";
export { AddBackstoryFactReducer };
import AddTruthAnchorReducer from "./add_truth_anchor_reducer";
export { AddTruthAnchorReducer };
import ApplyFrugImpactReducer from "./apply_frug_impact_reducer";
export { ApplyFrugImpactReducer };
import ApplyRelationshipEventReducer from "./apply_relationship_event_reducer";
export { ApplyRelationshipEventReducer };
import CanTradeWithNpcReducer from "./can_trade_with_npc_reducer";
export { CanTradeWithNpcReducer };
import ComputeInterestSetReducer from "./compute_interest_set_reducer";
export { ComputeInterestSetReducer };
import DebugApplyNeedsEffectReducer from "./debug_apply_needs_effect_reducer";
export { DebugApplyNeedsEffectReducer };
import DebugClearEventsReducer from "./debug_clear_events_reducer";
export { DebugClearEventsReducer };
import DebugGenerateChunkReducer from "./debug_generate_chunk_reducer";
export { DebugGenerateChunkReducer };
import DebugGetRelationshipReducer from "./debug_get_relationship_reducer";
export { DebugGetRelationshipReducer };
import DebugGetUtilitiesReducer from "./debug_get_utilities_reducer";
export { DebugGetUtilitiesReducer };
import DebugKillReducer from "./debug_kill_reducer";
export { DebugKillReducer };
import DebugReviveReducer from "./debug_revive_reducer";
export { DebugReviveReducer };
import DebugSpawnNpcReducer from "./debug_spawn_npc_reducer";
export { DebugSpawnNpcReducer };
import DebugTeleportReducer from "./debug_teleport_reducer";
export { DebugTeleportReducer };
import DebugUpdateNpcAiReducer from "./debug_update_npc_ai_reducer";
export { DebugUpdateNpcAiReducer };
import DehydrateNpcReducer from "./dehydrate_npc_reducer";
export { DehydrateNpcReducer };
import DespawnEntityReducer from "./despawn_entity_reducer";
export { DespawnEntityReducer };
import DialogueNpcRespondReducer from "./dialogue_npc_respond_reducer";
export { DialogueNpcRespondReducer };
import DialogueSayReducer from "./dialogue_say_reducer";
export { DialogueSayReducer };
import DumpNpcStateReducer from "./dump_npc_state_reducer";
export { DumpNpcStateReducer };
import EndDialogueReducer from "./end_dialogue_reducer";
export { EndDialogueReducer };
import EnsureChunksAroundReducer from "./ensure_chunks_around_reducer";
export { EnsureChunksAroundReducer };
import ForceInterestUpdateReducer from "./force_interest_update_reducer";
export { ForceInterestUpdateReducer };
import GenerateChunkReducer from "./generate_chunk_reducer";
export { GenerateChunkReducer };
import GenerateNpcBlueprintReducer from "./generate_npc_blueprint_reducer";
export { GenerateNpcBlueprintReducer };
import GetBlueprintForDialogueReducer from "./get_blueprint_for_dialogue_reducer";
export { GetBlueprintForDialogueReducer };
import GetChunkReducer from "./get_chunk_reducer";
export { GetChunkReducer };
import GetChunkDetailsReducer from "./get_chunk_details_reducer";
export { GetChunkDetailsReducer };
import GetChunkNpcsReducer from "./get_chunk_npcs_reducer";
export { GetChunkNpcsReducer };
import GetDialogueContextReducer from "./get_dialogue_context_reducer";
export { GetDialogueContextReducer };
import GetEntityEventsReducer from "./get_entity_events_reducer";
export { GetEntityEventsReducer };
import GetInterestSetDetailsReducer from "./get_interest_set_details_reducer";
export { GetInterestSetDetailsReducer };
import GetKnownNpcsReducer from "./get_known_npcs_reducer";
export { GetKnownNpcsReducer };
import GetLodDistributionReducer from "./get_lod_distribution_reducer";
export { GetLodDistributionReducer };
import GetMyFrugStateReducer from "./get_my_frug_state_reducer";
export { GetMyFrugStateReducer };
import GetNpcBlueprintReducer from "./get_npc_blueprint_reducer";
export { GetNpcBlueprintReducer };
import GetPendingNpcUpdatesReducer from "./get_pending_npc_updates_reducer";
export { GetPendingNpcUpdatesReducer };
import GetPlayerRelationshipsReducer from "./get_player_relationships_reducer";
export { GetPlayerRelationshipsReducer };
import GetRelationshipReducer from "./get_relationship_reducer";
export { GetRelationshipReducer };
import GetServerMetricsReducer from "./get_server_metrics_reducer";
export { GetServerMetricsReducer };
import GetServerStateReducer from "./get_server_state_reducer";
export { GetServerStateReducer };
import GetServerTickReducer from "./get_server_tick_reducer";
export { GetServerTickReducer };
import HydrateNpcReducer from "./hydrate_npc_reducer";
export { HydrateNpcReducer };
import KillEntityReducer from "./kill_entity_reducer";
export { KillEntityReducer };
import NewWorldSeedReducer from "./new_world_seed_reducer";
export { NewWorldSeedReducer };
import PerformGestureReducer from "./perform_gesture_reducer";
export { PerformGestureReducer };
import PlayerConnectReducer from "./player_connect_reducer";
export { PlayerConnectReducer };
import PlayerDisconnectReducer from "./player_disconnect_reducer";
export { PlayerDisconnectReducer };
import QueryEventsReducer from "./query_events_reducer";
export { QueryEventsReducer };
import RecordFrugDistanceReducer from "./record_frug_distance_reducer";
export { RecordFrugDistanceReducer };
import RecordItemCollectedReducer from "./record_item_collected_reducer";
export { RecordItemCollectedReducer };
import ReviveEntityReducer from "./revive_entity_reducer";
export { ReviveEntityReducer };
import SaveFrugStateReducer from "./save_frug_state_reducer";
export { SaveFrugStateReducer };
import SendMessageReducer from "./send_message_reducer";
export { SendMessageReducer };
import ServerTickReducer from "./server_tick_reducer";
export { ServerTickReducer };
import SetFrugActivityReducer from "./set_frug_activity_reducer";
export { SetFrugActivityReducer };
import SetLlmBlueprintReducer from "./set_llm_blueprint_reducer";
export { SetLlmBlueprintReducer };
import SetRelationshipFlagReducer from "./set_relationship_flag_reducer";
export { SetRelationshipFlagReducer };
import SpawnEntityReducer from "./spawn_entity_reducer";
export { SpawnEntityReducer };
import SpawnNpcReducer from "./spawn_npc_reducer";
export { SpawnNpcReducer };
import StartDialogueReducer from "./start_dialogue_reducer";
export { StartDialogueReducer };
import SubmitInputReducer from "./submit_input_reducer";
export { SubmitInputReducer };
import SubscribeChunksReducer from "./subscribe_chunks_reducer";
export { SubscribeChunksReducer };
import TeleportEntityReducer from "./teleport_entity_reducer";
export { TeleportEntityReducer };
import UpdateConversationSummaryReducer from "./update_conversation_summary_reducer";
export { UpdateConversationSummaryReducer };
import UpdateRelationshipReducer from "./update_relationship_reducer";
export { UpdateRelationshipReducer };
import YellMessageReducer from "./yell_message_reducer";
export { YellMessageReducer };

// Import and reexport all procedure arg types

// Import and reexport all table handle types
import ActiveDialogueRow from "./active_dialogue_table";
export { ActiveDialogueRow };
import ChunkRow from "./chunk_table";
export { ChunkRow };
import ChunkDeltaIndexRow from "./chunk_delta_index_table";
export { ChunkDeltaIndexRow };
import DialogueRateLimitRow from "./dialogue_rate_limit_table";
export { DialogueRateLimitRow };
import EntityRow from "./entity_table";
export { EntityRow };
import EventLogRow from "./event_log_table";
export { EventLogRow };
import FrugStateRow from "./frug_state_table";
export { FrugStateRow };
import IdCounterRow from "./id_counter_table";
export { IdCounterRow };
import InputQueueRow from "./input_queue_table";
export { InputQueueRow };
import InteractableRow from "./interactable_table";
export { InteractableRow };
import NpcBlueprintRow from "./npc_blueprint_table";
export { NpcBlueprintRow };
import NpcNpcRelationshipRow from "./npc_npc_relationship_table";
export { NpcNpcRelationshipRow };
import NpcPerceptionRow from "./npc_perception_table";
export { NpcPerceptionRow };
import NpcPersonalityEvolutionRow from "./npc_personality_evolution_table";
export { NpcPersonalityEvolutionRow };
import NpcReputationRow from "./npc_reputation_table";
export { NpcReputationRow };
import NpcRewardProfileRow from "./npc_reward_profile_table";
export { NpcRewardProfileRow };
import NpcScheduleRow from "./npc_schedule_table";
export { NpcScheduleRow };
import NpcSkillsRow from "./npc_skills_table";
export { NpcSkillsRow };
import NpcStateRow from "./npc_state_table";
export { NpcStateRow };
import PlayerRow from "./player_table";
export { PlayerRow };
import PlayerInterestRow from "./player_interest_table";
export { PlayerInterestRow };
import RelationshipRow from "./relationship_table";
export { RelationshipRow };
import ServerStateRow from "./server_state_table";
export { ServerStateRow };
import ServerTickScheduledRow from "./server_tick_scheduled_table";
export { ServerTickScheduledRow };
import TransformRow from "./transform_table";
export { TransformRow };
import WorldMessageRow from "./world_message_table";
export { WorldMessageRow };

// Import and reexport all types
import ActiveDialogue from "./active_dialogue_type";
export { ActiveDialogue };
import Chunk from "./chunk_type";
export { Chunk };
import ChunkDeltaIndex from "./chunk_delta_index_type";
export { ChunkDeltaIndex };
import DialogueRateLimit from "./dialogue_rate_limit_type";
export { DialogueRateLimit };
import Entity from "./entity_type";
export { Entity };
import EventLog from "./event_log_type";
export { EventLog };
import FrugState from "./frug_state_type";
export { FrugState };
import IdCounter from "./id_counter_type";
export { IdCounter };
import InputQueue from "./input_queue_type";
export { InputQueue };
import Interactable from "./interactable_type";
export { Interactable };
import NpcBlueprint from "./npc_blueprint_type";
export { NpcBlueprint };
import NpcNpcRelationship from "./npc_npc_relationship_type";
export { NpcNpcRelationship };
import NpcPerception from "./npc_perception_type";
export { NpcPerception };
import NpcPersonalityEvolution from "./npc_personality_evolution_type";
export { NpcPersonalityEvolution };
import NpcReputation from "./npc_reputation_type";
export { NpcReputation };
import NpcRewardProfile from "./npc_reward_profile_type";
export { NpcRewardProfile };
import NpcSchedule from "./npc_schedule_type";
export { NpcSchedule };
import NpcSkills from "./npc_skills_type";
export { NpcSkills };
import NpcState from "./npc_state_type";
export { NpcState };
import Player from "./player_type";
export { Player };
import PlayerInterest from "./player_interest_type";
export { PlayerInterest };
import Relationship from "./relationship_type";
export { Relationship };
import ServerState from "./server_state_type";
export { ServerState };
import ServerTickScheduled from "./server_tick_scheduled_type";
export { ServerTickScheduled };
import Transform from "./transform_type";
export { Transform };
import WorldMessage from "./world_message_type";
export { WorldMessage };

/** The schema information for all tables in this module. This is defined the same was as the tables would have been defined in the server. */
const tablesSchema = __schema(
  __table({
    name: 'active_dialogue',
    indexes: [
      { name: 'player_id', algorithm: 'btree', columns: [
        'playerId',
      ] },
    ],
    constraints: [
      { name: 'active_dialogue_player_id_key', constraint: 'unique', columns: ['playerId'] },
    ],
  }, ActiveDialogueRow),
  __table({
    name: 'chunk',
    indexes: [
      { name: 'chunk_id', algorithm: 'btree', columns: [
        'chunkId',
      ] },
      { name: 'cx', algorithm: 'btree', columns: [
        'cx',
      ] },
      { name: 'cy', algorithm: 'btree', columns: [
        'cy',
      ] },
    ],
    constraints: [
      { name: 'chunk_chunk_id_key', constraint: 'unique', columns: ['chunkId'] },
    ],
  }, ChunkRow),
  __table({
    name: 'chunk_delta_index',
    indexes: [
      { name: 'cx', algorithm: 'btree', columns: [
        'cx',
      ] },
      { name: 'cy', algorithm: 'btree', columns: [
        'cy',
      ] },
      { name: 'delta_index_id', algorithm: 'btree', columns: [
        'deltaIndexId',
      ] },
    ],
    constraints: [
      { name: 'chunk_delta_index_delta_index_id_key', constraint: 'unique', columns: ['deltaIndexId'] },
    ],
  }, ChunkDeltaIndexRow),
  __table({
    name: 'dialogue_rate_limit',
    indexes: [
      { name: 'npc_id', algorithm: 'btree', columns: [
        'npcId',
      ] },
    ],
    constraints: [
      { name: 'dialogue_rate_limit_npc_id_key', constraint: 'unique', columns: ['npcId'] },
    ],
  }, DialogueRateLimitRow),
  __table({
    name: 'entity',
    indexes: [
      { name: 'chunk_x', algorithm: 'btree', columns: [
        'chunkX',
      ] },
      { name: 'chunk_y', algorithm: 'btree', columns: [
        'chunkY',
      ] },
      { name: 'entity_id', algorithm: 'btree', columns: [
        'entityId',
      ] },
      { name: 'zone_id', algorithm: 'btree', columns: [
        'zoneId',
      ] },
    ],
    constraints: [
      { name: 'entity_entity_id_key', constraint: 'unique', columns: ['entityId'] },
    ],
  }, EntityRow),
  __table({
    name: 'event_log',
    indexes: [
      { name: 'event_id', algorithm: 'btree', columns: [
        'eventId',
      ] },
      { name: 'event_type', algorithm: 'btree', columns: [
        'eventType',
      ] },
    ],
    constraints: [
      { name: 'event_log_event_id_key', constraint: 'unique', columns: ['eventId'] },
    ],
  }, EventLogRow),
  __table({
    name: 'frug_state',
    indexes: [
      { name: 'player_id', algorithm: 'btree', columns: [
        'playerId',
      ] },
    ],
    constraints: [
      { name: 'frug_state_player_id_key', constraint: 'unique', columns: ['playerId'] },
    ],
  }, FrugStateRow),
  __table({
    name: 'id_counter',
    indexes: [
      { name: 'name', algorithm: 'btree', columns: [
        'name',
      ] },
    ],
    constraints: [
      { name: 'id_counter_name_key', constraint: 'unique', columns: ['name'] },
    ],
  }, IdCounterRow),
  __table({
    name: 'input_queue',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'player_id', algorithm: 'btree', columns: [
        'playerId',
      ] },
    ],
    constraints: [
      { name: 'input_queue_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, InputQueueRow),
  __table({
    name: 'interactable',
    indexes: [
      { name: 'chunk_x', algorithm: 'btree', columns: [
        'chunkX',
      ] },
      { name: 'chunk_y', algorithm: 'btree', columns: [
        'chunkY',
      ] },
      { name: 'interactable_id', algorithm: 'btree', columns: [
        'interactableId',
      ] },
    ],
    constraints: [
      { name: 'interactable_interactable_id_key', constraint: 'unique', columns: ['interactableId'] },
    ],
  }, InteractableRow),
  __table({
    name: 'npc_blueprint',
    indexes: [
      { name: 'npc_id', algorithm: 'btree', columns: [
        'npcId',
      ] },
    ],
    constraints: [
      { name: 'npc_blueprint_npc_id_key', constraint: 'unique', columns: ['npcId'] },
    ],
  }, NpcBlueprintRow),
  __table({
    name: 'npc_npc_relationship',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'npc_a_id', algorithm: 'btree', columns: [
        'npcAId',
      ] },
      { name: 'npc_b_id', algorithm: 'btree', columns: [
        'npcBId',
      ] },
    ],
    constraints: [
      { name: 'npc_npc_relationship_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, NpcNpcRelationshipRow),
  __table({
    name: 'npc_perception',
    indexes: [
      { name: 'npc_id', algorithm: 'btree', columns: [
        'npcId',
      ] },
      { name: 'perception_id', algorithm: 'btree', columns: [
        'perceptionId',
      ] },
    ],
    constraints: [
      { name: 'npc_perception_perception_id_key', constraint: 'unique', columns: ['perceptionId'] },
    ],
  }, NpcPerceptionRow),
  __table({
    name: 'npc_personality_evolution',
    indexes: [
      { name: 'npc_id', algorithm: 'btree', columns: [
        'npcId',
      ] },
    ],
    constraints: [
      { name: 'npc_personality_evolution_npc_id_key', constraint: 'unique', columns: ['npcId'] },
    ],
  }, NpcPersonalityEvolutionRow),
  __table({
    name: 'npc_reputation',
    indexes: [
      { name: 'npc_id', algorithm: 'btree', columns: [
        'npcId',
      ] },
    ],
    constraints: [
      { name: 'npc_reputation_npc_id_key', constraint: 'unique', columns: ['npcId'] },
    ],
  }, NpcReputationRow),
  __table({
    name: 'npc_reward_profile',
    indexes: [
      { name: 'npc_id', algorithm: 'btree', columns: [
        'npcId',
      ] },
    ],
    constraints: [
      { name: 'npc_reward_profile_npc_id_key', constraint: 'unique', columns: ['npcId'] },
    ],
  }, NpcRewardProfileRow),
  __table({
    name: 'npc_schedule',
    indexes: [
      { name: 'npc_id', algorithm: 'btree', columns: [
        'npcId',
      ] },
    ],
    constraints: [
      { name: 'npc_schedule_npc_id_key', constraint: 'unique', columns: ['npcId'] },
    ],
  }, NpcScheduleRow),
  __table({
    name: 'npc_skills',
    indexes: [
      { name: 'npc_id', algorithm: 'btree', columns: [
        'npcId',
      ] },
    ],
    constraints: [
      { name: 'npc_skills_npc_id_key', constraint: 'unique', columns: ['npcId'] },
    ],
  }, NpcSkillsRow),
  __table({
    name: 'npc_state',
    indexes: [
      { name: 'npc_id', algorithm: 'btree', columns: [
        'npcId',
      ] },
    ],
    constraints: [
      { name: 'npc_state_npc_id_key', constraint: 'unique', columns: ['npcId'] },
    ],
  }, NpcStateRow),
  __table({
    name: 'player',
    indexes: [
      { name: 'entity_id', algorithm: 'btree', columns: [
        'entityId',
      ] },
      { name: 'identity', algorithm: 'btree', columns: [
        'identity',
      ] },
    ],
    constraints: [
      { name: 'player_entity_id_key', constraint: 'unique', columns: ['entityId'] },
      { name: 'player_identity_key', constraint: 'unique', columns: ['identity'] },
    ],
  }, PlayerRow),
  __table({
    name: 'player_interest',
    indexes: [
      { name: 'player_id', algorithm: 'btree', columns: [
        'playerId',
      ] },
    ],
    constraints: [
      { name: 'player_interest_player_id_key', constraint: 'unique', columns: ['playerId'] },
    ],
  }, PlayerInterestRow),
  __table({
    name: 'relationship',
    indexes: [
      { name: 'npc_id', algorithm: 'btree', columns: [
        'npcId',
      ] },
      { name: 'player_id', algorithm: 'btree', columns: [
        'playerId',
      ] },
      { name: 'relationship_id', algorithm: 'btree', columns: [
        'relationshipId',
      ] },
    ],
    constraints: [
      { name: 'relationship_relationship_id_key', constraint: 'unique', columns: ['relationshipId'] },
    ],
  }, RelationshipRow),
  __table({
    name: 'server_state',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'server_state_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, ServerStateRow),
  __table({
    name: 'server_tick_scheduled',
    indexes: [
      { name: 'scheduled_id', algorithm: 'btree', columns: [
        'scheduledId',
      ] },
    ],
    constraints: [
      { name: 'server_tick_scheduled_scheduled_id_key', constraint: 'unique', columns: ['scheduledId'] },
    ],
  }, ServerTickScheduledRow),
  __table({
    name: 'transform',
    indexes: [
      { name: 'entity_id', algorithm: 'btree', columns: [
        'entityId',
      ] },
    ],
    constraints: [
      { name: 'transform_entity_id_key', constraint: 'unique', columns: ['entityId'] },
    ],
  }, TransformRow),
  __table({
    name: 'world_message',
    indexes: [
      { name: 'chunk_x', algorithm: 'btree', columns: [
        'chunkX',
      ] },
      { name: 'chunk_y', algorithm: 'btree', columns: [
        'chunkY',
      ] },
      { name: 'message_id', algorithm: 'btree', columns: [
        'messageId',
      ] },
      { name: 'sender_id', algorithm: 'btree', columns: [
        'senderId',
      ] },
    ],
    constraints: [
      { name: 'world_message_message_id_key', constraint: 'unique', columns: ['messageId'] },
    ],
  }, WorldMessageRow),
);

/** The schema information for all reducers in this module. This is defined the same way as the reducers would have been defined in the server, except the body of the reducer is omitted in code generation. */
const reducersSchema = __reducers(
  __reducerSchema("add_backstory_fact", AddBackstoryFactReducer),
  __reducerSchema("add_truth_anchor", AddTruthAnchorReducer),
  __reducerSchema("apply_frug_impact", ApplyFrugImpactReducer),
  __reducerSchema("apply_relationship_event", ApplyRelationshipEventReducer),
  __reducerSchema("can_trade_with_npc", CanTradeWithNpcReducer),
  __reducerSchema("compute_interest_set", ComputeInterestSetReducer),
  __reducerSchema("debug_apply_needs_effect", DebugApplyNeedsEffectReducer),
  __reducerSchema("debug_clear_events", DebugClearEventsReducer),
  __reducerSchema("debug_generate_chunk", DebugGenerateChunkReducer),
  __reducerSchema("debug_get_relationship", DebugGetRelationshipReducer),
  __reducerSchema("debug_get_utilities", DebugGetUtilitiesReducer),
  __reducerSchema("debug_kill", DebugKillReducer),
  __reducerSchema("debug_revive", DebugReviveReducer),
  __reducerSchema("debug_spawn_npc", DebugSpawnNpcReducer),
  __reducerSchema("debug_teleport", DebugTeleportReducer),
  __reducerSchema("debug_update_npc_ai", DebugUpdateNpcAiReducer),
  __reducerSchema("dehydrate_npc", DehydrateNpcReducer),
  __reducerSchema("despawn_entity", DespawnEntityReducer),
  __reducerSchema("dialogue_npc_respond", DialogueNpcRespondReducer),
  __reducerSchema("dialogue_say", DialogueSayReducer),
  __reducerSchema("dump_npc_state", DumpNpcStateReducer),
  __reducerSchema("end_dialogue", EndDialogueReducer),
  __reducerSchema("ensure_chunks_around", EnsureChunksAroundReducer),
  __reducerSchema("force_interest_update", ForceInterestUpdateReducer),
  __reducerSchema("generate_chunk", GenerateChunkReducer),
  __reducerSchema("generate_npc_blueprint", GenerateNpcBlueprintReducer),
  __reducerSchema("get_blueprint_for_dialogue", GetBlueprintForDialogueReducer),
  __reducerSchema("get_chunk", GetChunkReducer),
  __reducerSchema("get_chunk_details", GetChunkDetailsReducer),
  __reducerSchema("get_chunk_npcs", GetChunkNpcsReducer),
  __reducerSchema("get_dialogue_context", GetDialogueContextReducer),
  __reducerSchema("get_entity_events", GetEntityEventsReducer),
  __reducerSchema("get_interest_set_details", GetInterestSetDetailsReducer),
  __reducerSchema("get_known_npcs", GetKnownNpcsReducer),
  __reducerSchema("get_lod_distribution", GetLodDistributionReducer),
  __reducerSchema("get_my_frug_state", GetMyFrugStateReducer),
  __reducerSchema("get_npc_blueprint", GetNpcBlueprintReducer),
  __reducerSchema("get_pending_npc_updates", GetPendingNpcUpdatesReducer),
  __reducerSchema("get_player_relationships", GetPlayerRelationshipsReducer),
  __reducerSchema("get_relationship", GetRelationshipReducer),
  __reducerSchema("get_server_metrics", GetServerMetricsReducer),
  __reducerSchema("get_server_state", GetServerStateReducer),
  __reducerSchema("get_server_tick", GetServerTickReducer),
  __reducerSchema("hydrate_npc", HydrateNpcReducer),
  __reducerSchema("kill_entity", KillEntityReducer),
  __reducerSchema("new_world_seed", NewWorldSeedReducer),
  __reducerSchema("perform_gesture", PerformGestureReducer),
  __reducerSchema("player_connect", PlayerConnectReducer),
  __reducerSchema("player_disconnect", PlayerDisconnectReducer),
  __reducerSchema("query_events", QueryEventsReducer),
  __reducerSchema("record_frug_distance", RecordFrugDistanceReducer),
  __reducerSchema("record_item_collected", RecordItemCollectedReducer),
  __reducerSchema("revive_entity", ReviveEntityReducer),
  __reducerSchema("save_frug_state", SaveFrugStateReducer),
  __reducerSchema("send_message", SendMessageReducer),
  __reducerSchema("server_tick", ServerTickReducer),
  __reducerSchema("set_frug_activity", SetFrugActivityReducer),
  __reducerSchema("set_llm_blueprint", SetLlmBlueprintReducer),
  __reducerSchema("set_relationship_flag", SetRelationshipFlagReducer),
  __reducerSchema("spawn_entity", SpawnEntityReducer),
  __reducerSchema("spawn_npc", SpawnNpcReducer),
  __reducerSchema("start_dialogue", StartDialogueReducer),
  __reducerSchema("submit_input", SubmitInputReducer),
  __reducerSchema("subscribe_chunks", SubscribeChunksReducer),
  __reducerSchema("teleport_entity", TeleportEntityReducer),
  __reducerSchema("update_conversation_summary", UpdateConversationSummaryReducer),
  __reducerSchema("update_relationship", UpdateRelationshipReducer),
  __reducerSchema("yell_message", YellMessageReducer),
);

/** The schema information for all procedures in this module. This is defined the same way as the procedures would have been defined in the server. */
const proceduresSchema = __procedures(
);

/** The remote SpacetimeDB module schema, both runtime and type information. */
const REMOTE_MODULE = {
  versionInfo: {
    cliVersion: "1.11.1" as const,
  },
  tables: tablesSchema.schemaType.tables,
  reducers: reducersSchema.reducersType.reducers,
  ...proceduresSchema,
} satisfies __RemoteModule<
  typeof tablesSchema.schemaType,
  typeof reducersSchema.reducersType,
  typeof proceduresSchema
>;

/** The tables available in this remote SpacetimeDB module. */
export const tables = __convertToAccessorMap(tablesSchema.schemaType.tables);

/** The reducers available in this remote SpacetimeDB module. */
export const reducers = __convertToAccessorMap(reducersSchema.reducersType.reducers);

/** The context type returned in callbacks for all possible events. */
export type EventContext = __EventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for reducer events. */
export type ReducerEventContext = __ReducerEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for subscription events. */
export type SubscriptionEventContext = __SubscriptionEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for error events. */
export type ErrorContext = __ErrorContextInterface<typeof REMOTE_MODULE>;
/** The subscription handle type to manage active subscriptions created from a {@link SubscriptionBuilder}. */
export type SubscriptionHandle = __SubscriptionHandleImpl<typeof REMOTE_MODULE>;

/** Builder class to configure a new subscription to the remote SpacetimeDB instance. */
export class SubscriptionBuilder extends __SubscriptionBuilderImpl<typeof REMOTE_MODULE> {}

/** Builder class to configure a new database connection to the remote SpacetimeDB instance. */
export class DbConnectionBuilder extends __DbConnectionBuilder<DbConnection> {}

/** The typed database connection to manage connections to the remote SpacetimeDB instance. This class has type information specific to the generated module. */
export class DbConnection extends __DbConnectionImpl<typeof REMOTE_MODULE> {
  /** Creates a new {@link DbConnectionBuilder} to configure and connect to the remote SpacetimeDB instance. */
  static builder = (): DbConnectionBuilder => {
    return new DbConnectionBuilder(REMOTE_MODULE, (config: __DbConnectionConfig<typeof REMOTE_MODULE>) => new DbConnection(config));
  };

  /** Creates a new {@link SubscriptionBuilder} to configure a subscription to the remote SpacetimeDB instance. */
  override subscriptionBuilder = (): SubscriptionBuilder => {
    return new SubscriptionBuilder(this);
  };
}

