// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.object("InputQueue", {
  id: __t.u64(),
  playerId: __t.u64(),
  inputSeq: __t.u32(),
  clientTimeMs: __t.u64(),
  moveX: __t.i16(),
  moveY: __t.i16(),
  actions: __t.u32(),
  aimYaw: __t.i16(),
  predictedX: __t.i32(),
  predictedY: __t.i32(),
  predictedZ: __t.i32(),
});


