// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.object("Interactable", {
  interactableId: __t.u64(),
  chunkX: __t.i32(),
  chunkY: __t.i32(),
  zoneId: __t.u64(),
  localX: __t.i32(),
  localY: __t.i32(),
  itype: __t.u16(),
  subtype: __t.u32(),
  resourceAmount: __t.u16(),
  resourceMax: __t.u16(),
  regenRate: __t.u8(),
  ownerId: __t.option(__t.u64()),
  quality: __t.u8(),
  flags: __t.u32(),
  lastInteractTick: __t.u64(),
});


