// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.object("NpcState", {
  npcId: __t.u64(),
  lodState: __t.u8(),
  longGoal: __t.byteArray(),
  midGoal: __t.byteArray(),
  shortIntent: __t.byteArray(),
  needs: __t.byteArray(),
  memorySummary: __t.byteArray(),
  lastReplanTsMs: __t.u64(),
});


