// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.object("NpcPerception", {
  perceptionId: __t.u64(),
  npcId: __t.u64(),
  thought: __t.string(),
  sourceEntityId: __t.u64(),
  perceptionType: __t.string(),
  createdTsMs: __t.u64(),
  expiresTsMs: __t.u64(),
});


