// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  npcId: __t.u64().primaryKey().name("npc_id"),
  wakeHour: __t.u8().name("wake_hour"),
  sleepHour: __t.u8().name("sleep_hour"),
  scheduleJson: __t.byteArray().name("schedule_json"),
  ritualsJson: __t.byteArray().name("rituals_json"),
  scheduleSeed: __t.u64().name("schedule_seed"),
});
