// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  entityId: __t.u64().primaryKey().name("entity_id"),
  x: __t.i32(),
  y: __t.i32(),
  z: __t.i32(),
  yaw: __t.i16(),
  vx: __t.i16(),
  vy: __t.i16(),
  vz: __t.i16(),
  lastTick: __t.u64().name("last_tick"),
});
