// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  messageId: __t.u64().primaryKey().name("message_id"),
  senderId: __t.u64().name("sender_id"),
  senderName: __t.string().name("sender_name"),
  message: __t.string(),
  isYell: __t.bool().name("is_yell"),
  chunkX: __t.i32().name("chunk_x"),
  chunkY: __t.i32().name("chunk_y"),
  posX: __t.i32().name("pos_x"),
  posY: __t.i32().name("pos_y"),
  posZ: __t.i32().name("pos_z"),
  tsMs: __t.u64().name("ts_ms"),
  expiresTsMs: __t.u64().name("expires_ts_ms"),
});
