// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  playerId: __t.u64().primaryKey().name("player_id"),
  npcId: __t.u64().name("npc_id"),
  sessionId: __t.u64().name("session_id"),
  startedTsMs: __t.u64().name("started_ts_ms"),
  lastActivityTsMs: __t.u64().name("last_activity_ts_ms"),
  lineCount: __t.u32().name("line_count"),
  context: __t.byteArray(),
});
