// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  deltaIndexId: __t.u64().primaryKey().name("delta_index_id"),
  cx: __t.i32(),
  cy: __t.i32(),
  zoneId: __t.u64().name("zone_id"),
  lastCompactionTick: __t.u64().name("last_compaction_tick"),
  deltaBlob: __t.byteArray().name("delta_blob"),
});
