// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  eventId: __t.u64().primaryKey().name("event_id"),
  tsMs: __t.u64().name("ts_ms"),
  tick: __t.u64(),
  zoneId: __t.u64().name("zone_id"),
  chunkX: __t.i32().name("chunk_x"),
  chunkY: __t.i32().name("chunk_y"),
  actorId: __t.option(__t.u64()).name("actor_id"),
  targetId: __t.option(__t.u64()).name("target_id"),
  eventType: __t.u16().name("event_type"),
  payload: __t.byteArray(),
});
