// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  playerId: __t.u64().primaryKey().name("player_id"),
  health: __t.u8(),
  maxHealth: __t.u8().name("max_health"),
  energy: __t.u8(),
  maxEnergy: __t.u8().name("max_energy"),
  hunger: __t.u8(),
  thirst: __t.u8(),
  fatigue: __t.u8(),
  cleanliness: __t.u8(),
  happiness: __t.u8(),
  stress: __t.u8(),
  comfort: __t.u8(),
  excitement: __t.u8(),
  curiosity: __t.u8(),
  confidence: __t.u8(),
  loneliness: __t.u8(),
  friendshipLevel: __t.u8().name("friendship_level"),
  reputation: __t.u8(),
  charisma: __t.u8(),
  lastSocialTsMs: __t.u64().name("last_social_ts_ms"),
  activity: __t.u8(),
  currentBiome: __t.u16().name("current_biome"),
  ageTicks: __t.u64().name("age_ticks"),
  totalDistanceMm: __t.u64().name("total_distance_mm"),
  totalNpcInteractions: __t.u32().name("total_npc_interactions"),
  totalItemsCollected: __t.u32().name("total_items_collected"),
  lastDecayTick: __t.u64().name("last_decay_tick"),
  lastUpdatedTsMs: __t.u64().name("last_updated_ts_ms"),
  createdTsMs: __t.u64().name("created_ts_ms"),
});
