// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.object("FrugState", {
  playerId: __t.u64(),
  health: __t.u8(),
  maxHealth: __t.u8(),
  energy: __t.u8(),
  maxEnergy: __t.u8(),
  hunger: __t.u8(),
  thirst: __t.u8(),
  fatigue: __t.u8(),
  cleanliness: __t.u8(),
  happiness: __t.u8(),
  stress: __t.u8(),
  comfort: __t.u8(),
  excitement: __t.u8(),
  curiosity: __t.u8(),
  confidence: __t.u8(),
  loneliness: __t.u8(),
  friendshipLevel: __t.u8(),
  reputation: __t.u8(),
  charisma: __t.u8(),
  lastSocialTsMs: __t.u64(),
  activity: __t.u8(),
  currentBiome: __t.u16(),
  ageTicks: __t.u64(),
  totalDistanceMm: __t.u64(),
  totalNpcInteractions: __t.u32(),
  totalItemsCollected: __t.u32(),
  lastDecayTick: __t.u64(),
  lastUpdatedTsMs: __t.u64(),
  createdTsMs: __t.u64(),
});


