// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  playerId: __t.u64().name("player_id"),
  inputSeq: __t.u32().name("input_seq"),
  clientTimeMs: __t.u64().name("client_time_ms"),
  moveX: __t.i16().name("move_x"),
  moveY: __t.i16().name("move_y"),
  actions: __t.u32(),
  aimYaw: __t.i16().name("aim_yaw"),
  predictedX: __t.i32().name("predicted_x"),
  predictedY: __t.i32().name("predicted_y"),
  predictedZ: __t.i32().name("predicted_z"),
});
