// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  interactableId: __t.u64().primaryKey().name("interactable_id"),
  chunkX: __t.i32().name("chunk_x"),
  chunkY: __t.i32().name("chunk_y"),
  zoneId: __t.u64().name("zone_id"),
  localX: __t.i32().name("local_x"),
  localY: __t.i32().name("local_y"),
  itype: __t.u16(),
  subtype: __t.u32(),
  resourceAmount: __t.u16().name("resource_amount"),
  resourceMax: __t.u16().name("resource_max"),
  regenRate: __t.u8().name("regen_rate"),
  ownerId: __t.option(__t.u64()).name("owner_id"),
  quality: __t.u8(),
  flags: __t.u32(),
  lastInteractTick: __t.u64().name("last_interact_tick"),
});
