// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  perceptionId: __t.u64().primaryKey().name("perception_id"),
  npcId: __t.u64().name("npc_id"),
  thought: __t.string(),
  sourceEntityId: __t.u64().name("source_entity_id"),
  perceptionType: __t.string().name("perception_type"),
  createdTsMs: __t.u64().name("created_ts_ms"),
  expiresTsMs: __t.u64().name("expires_ts_ms"),
});
