// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.object("NpcPersonalityEvolution", {
  npcId: __t.u64(),
  traitsJson: __t.byteArray(),
  virtuesVicesJson: __t.byteArray(),
  goalsJson: __t.byteArray(),
  stability: __t.u8(),
  lifeStage: __t.u8(),
  ageTicks: __t.u64(),
  lastUpdateTick: __t.u64(),
  version: __t.u16(),
});


