// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.object("NpcNpcRelationship", {
  id: __t.u64(),
  npcAId: __t.u64(),
  npcBId: __t.u64(),
  affinityAToB: __t.i16(),
  affinityBToA: __t.i16(),
  trustAToB: __t.i16(),
  trustBToA: __t.i16(),
  interactionCount: __t.u32(),
  lastInteractionTick: __t.u64(),
  relationshipType: __t.u16(),
  flags: __t.u32(),
  sharedKnowledge: __t.byteArray(),
});


