// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  npcId: __t.u64().primaryKey().name("npc_id"),
  lodState: __t.u8().name("lod_state"),
  longGoal: __t.byteArray().name("long_goal"),
  midGoal: __t.byteArray().name("mid_goal"),
  shortIntent: __t.byteArray().name("short_intent"),
  needs: __t.byteArray(),
  memorySummary: __t.byteArray().name("memory_summary"),
  lastReplanTsMs: __t.u64().name("last_replan_ts_ms"),
});
