// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  npcId: __t.u64().primaryKey().name("npc_id"),
  tradeRep: __t.i16().name("trade_rep"),
  combatRep: __t.i16().name("combat_rep"),
  socialRep: __t.i16().name("social_rep"),
  knowledgeRep: __t.i16().name("knowledge_rep"),
  criminalRep: __t.u16().name("criminal_rep"),
  homeChunkX: __t.i32().name("home_chunk_x"),
  homeChunkY: __t.i32().name("home_chunk_y"),
  localRep: __t.u8().name("local_rep"),
  deedsJson: __t.byteArray().name("deeds_json"),
  regionalJson: __t.byteArray().name("regional_json"),
  lastUpdateTick: __t.u64().name("last_update_tick"),
  version: __t.u16(),
});
