// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  npcId: __t.u64().primaryKey().name("npc_id"),
  traitsJson: __t.byteArray().name("traits_json"),
  virtuesVicesJson: __t.byteArray().name("virtues_vices_json"),
  goalsJson: __t.byteArray().name("goals_json"),
  stability: __t.u8(),
  lifeStage: __t.u8().name("life_stage"),
  ageTicks: __t.u64().name("age_ticks"),
  lastUpdateTick: __t.u64().name("last_update_tick"),
  version: __t.u16(),
});
