// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  npcAId: __t.u64().name("npc_a_id"),
  npcBId: __t.u64().name("npc_b_id"),
  affinityAToB: __t.i16().name("affinity_a_to_b"),
  affinityBToA: __t.i16().name("affinity_b_to_a"),
  trustAToB: __t.i16().name("trust_a_to_b"),
  trustBToA: __t.i16().name("trust_b_to_a"),
  interactionCount: __t.u32().name("interaction_count"),
  lastInteractionTick: __t.u64().name("last_interaction_tick"),
  relationshipType: __t.u16().name("relationship_type"),
  flags: __t.u32(),
  sharedKnowledge: __t.byteArray().name("shared_knowledge"),
});
