// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.object("NpcSchedule", {
  npcId: __t.u64(),
  wakeHour: __t.u8(),
  sleepHour: __t.u8(),
  scheduleJson: __t.byteArray(),
  ritualsJson: __t.byteArray(),
  scheduleSeed: __t.u64(),
});


