// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.object("NpcReputation", {
  npcId: __t.u64(),
  tradeRep: __t.i16(),
  combatRep: __t.i16(),
  socialRep: __t.i16(),
  knowledgeRep: __t.i16(),
  criminalRep: __t.u16(),
  homeChunkX: __t.i32(),
  homeChunkY: __t.i32(),
  localRep: __t.u8(),
  deedsJson: __t.byteArray(),
  regionalJson: __t.byteArray(),
  lastUpdateTick: __t.u64(),
  version: __t.u16(),
});


