// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.object("Player", {
  identity: __t.identity(),
  entityId: __t.u64(),
  name: __t.string(),
  lastInputSeq: __t.u32(),
  connectedTsMs: __t.u64(),
  lastActivityTsMs: __t.u64(),
});


