// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  playerId: __t.u64().primaryKey().name("player_id"),
  currentChunkX: __t.i32().name("current_chunk_x"),
  currentChunkY: __t.i32().name("current_chunk_y"),
  entityIds: __t.byteArray().name("entity_ids"),
  lodByEntity: __t.byteArray().name("lod_by_entity"),
  chunkIds: __t.byteArray().name("chunk_ids"),
  lastUpdateTick: __t.u64().name("last_update_tick"),
});
