// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.object("PlayerInterest", {
  playerId: __t.u64(),
  currentChunkX: __t.i32(),
  currentChunkY: __t.i32(),
  entityIds: __t.byteArray(),
  lodByEntity: __t.byteArray(),
  chunkIds: __t.byteArray(),
  lastUpdateTick: __t.u64(),
});


