// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.object("Relationship", {
  relationshipId: __t.u64(),
  playerId: __t.u64(),
  npcId: __t.u64(),
  affinity: __t.i16(),
  trust: __t.i16(),
  flags: __t.u32(),
  conversationSummary: __t.byteArray(),
});


