// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.object("WorldMessage", {
  messageId: __t.u64(),
  senderId: __t.u64(),
  senderName: __t.string(),
  message: __t.string(),
  isYell: __t.bool(),
  chunkX: __t.i32(),
  chunkY: __t.i32(),
  posX: __t.i32(),
  posY: __t.i32(),
  posZ: __t.i32(),
  tsMs: __t.u64(),
  expiresTsMs: __t.u64(),
});


